import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hexleap Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="light" lang="en">
      <body className="{inter.className} dark:bg-[#292B32]">
        <div className=" container mx-auto m-8">{children}</div>
      </body>
    </html>
  );
}
